### ISSUE TITLE
Don't add data.go itself to bindata

### ISSUE THREAD

**Issue by sqs** [sourcegraph/appdash-data#2]
If we add data.go to bindata (as the current generate.go file does), then running `go generate` will result in changes to data.go in `git status` even if there were no changes to any actual data files. This adds a small amount of dev overhead and could result in erroneous commits.

The `go-bindata -ignore` option didn't seem to work for me, but maybe someone else will be able to figure it out.

**Comment by emidoots** [comment]
Got it sorted out by copying [Appdash](https://sourcegraph.com/sourcegraph.com/sourcegraph/appdash@ae6c67938db9e037fbac45bdb192550938d3a6d2/.tree/doc.go#startline=48&endline=48)'s usage of go-bindata. `go generate` should no longer do that.
